# Generated by Django 3.1.6 on 2021-02-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pila_nombreid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Fotos'),
        ),
    ]
