# Generated by Django 3.1.6 on 2021-02-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210204_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiaprima',
            options={'ordering': ('nombre',), 'verbose_name_plural': 'Materias Primas'},
        ),
    ]
