# Generated by Django 3.1.6 on 2021-02-09 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210205_0354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiaprima',
            old_name='medicion',
            new_name='pila',
        ),
        migrations.AlterField(
            model_name='medicion',
            name='pila',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pila'),
        ),
    ]
