# Generated by Django 3.1.6 on 2021-02-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210209_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicion',
            name='posicion',
        ),
        migrations.AddField(
            model_name='pila',
            name='posicion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='pila',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pila'),
        ),
    ]
