# Generated by Django 3.1.6 on 2021-02-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210222_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pila',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Fase I: mesófila'), (2, 'Fase II: termófila'), (3, 'Fase III: enfriamiento'), (4, 'Fase IV: maduración')], default=1),
        ),
    ]
