# Generated by Django 3.1.6 on 2021-02-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210222_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pila',
            name='estado',
            field=models.CharField(choices=[('mesófila', 'Fase I: mesófila'), ('termófila', 'Fase II: termófila'), ('enfriamiento', 'Fase III: enfriamiento'), ('maduración', 'Fase IV: maduración')], max_length=50),
        ),
    ]
