# Generated by Django 3.1.7 on 2021-05-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cuentausuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pila',
            name='foto',
        ),
        migrations.AddField(
            model_name='medicion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Fotos'),
        ),
    ]
