# Generated by Django 3.1.7 on 2021-05-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210511_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='pila',
            name='visitado',
            field=models.BooleanField(default=False),
        ),
    ]
